spring:
  datasource:
    url: jdbc:mysql://${prod.db.url}:3306/mydb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${prod.db.username}
    password: ${prod.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver