spring:
  profiles:
    include: secret
    active: prod

  jwt:
    secret: ${jwt.secret}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080  # HTTPS를 8080 포트에 적용

---
spring:
  config:
    activate:
      on-profile: dev
server:
  ssl:
    enabled: false  # 개발 환경에서는 SSL을 비활성화

---
spring:
  config:
    activate:
      on-profile: prod
server:
  ssl:
    enabled: true
    key-store: ${ssl.key-store}
    key-store-password: ${ssl.key-store-password}
    key-store-type: ${ssl.key-store-type}
    key-alias: ${ssl.key-alias}